"""Question bank for the Daily Practice page.

Structure: BANK[category][level] is a list of questions. Every list should have the
same length (QUESTIONS_PER_LIST) so the daily rotation stays in step.

To add questions: append to a list, then append the same number of questions to the
other five lists so they stay equal in length.

Each question is  q(text, [options], correct_option_index, explanation, code=None)
"""


def q(text, options, answer, explanation, code=None):
    return {"question": text, "options": options, "answer": answer,
            "explanation": explanation, "code": code}


CATEGORIES = [
    {"key": "english", "title": "English", "icon": "📚"},
    {"key": "reasoning", "title": "Logical Reasoning", "icon": "🧠"},
    {"key": "coding", "title": "Coding", "icon": "💻"},
]

# ---------------------------------------------------------------- ENGLISH
ENGLISH_BEGINNER = [
    q("Choose the correct word: She ___ to college every day.",
      ["go", "goes", "going", "gone"], 1,
      "With a singular subject (she/he/it) in the simple present, the verb takes -s/-es: she goes."),
    q("Which word means the same as \"happy\"?",
      ["Sad", "Angry", "Joyful", "Tired"], 2,
      "Joyful is a synonym of happy. Sad, angry and tired describe other feelings."),
    q("Choose the opposite (antonym) of \"ancient\".",
      ["Old", "Modern", "Historic", "Aged"], 1,
      "Ancient means very old, so its opposite is modern."),
    q("Fill in the blank: I have ___ umbrella.",
      ["a", "an", "the", "no article"], 1,
      "Use \"an\" before a vowel sound. Umbrella starts with the vowel sound /ʌ/."),
    q("What is the plural of \"child\"?",
      ["childs", "childes", "children", "childrens"], 2,
      "Child has an irregular plural: children."),
    q("What is the past tense of \"buy\"?",
      ["buyed", "bought", "boughten", "buys"], 1,
      "Buy is an irregular verb: buy, bought, bought."),
    q("Which spelling is correct?",
      ["Recieve", "Receve", "Receive", "Riceive"], 2,
      "Remember the rule: \"i before e, except after c\". So: receive."),
    q("Fill in the blank: He is good ___ mathematics.",
      ["in", "at", "on", "with"], 1,
      "The fixed phrase is \"good at\" a subject or skill."),
    q("Fill in the blank: If it rains, we ___ stay at home.",
      ["will", "would", "had", "did"], 0,
      "A real future condition uses: If + present simple, will + verb."),
    q("What does the idiom \"a piece of cake\" mean?",
      ["A sweet dessert", "Something very easy", "A small gift", "A birthday party"], 1,
      "\"A piece of cake\" means a task that is very easy."),
    q("Choose the correct sentence.",
      ["Neither of the boys are here.", "Neither of the boys is here.",
       "Neither of the boys were here.", "Neither of the boys be here."], 1,
      "\"Neither\" is singular, so it takes a singular verb: Neither of the boys is here."),
    q("Fill in the blank: There ___ many students in the lab.",
      ["is", "was", "are", "has"], 2,
      "\"Students\" is plural, so use \"are\"."),
    q("Choose one word for \"a person who writes books\".",
      ["Author", "Actor", "Editor", "Reader"], 0,
      "An author writes books. An editor corrects and prepares them for printing."),
    q("Fill in the blank: The meeting starts ___ 10 a.m.",
      ["in", "on", "at", "by"], 2,
      "Use \"at\" with exact clock times: at 10 a.m."),
    q("What is the comparative form of \"good\"?",
      ["gooder", "more good", "better", "best"], 2,
      "Good is irregular: good, better, best."),
]

ENGLISH_ADVANCED = [
    q("Choose the synonym of \"ephemeral\".",
      ["Everlasting", "Short-lived", "Powerful", "Hidden"], 1,
      "Ephemeral describes something that lasts for a very short time."),
    q("Choose the antonym of \"benevolent\".",
      ["Kind", "Generous", "Malevolent", "Cheerful"], 2,
      "Benevolent means well-meaning and kind. Malevolent means wishing harm to others."),
    q("Find the error: \"Each of the engineers have submitted their report.\"",
      ["Each of the", "engineers have", "submitted their report", "No error"], 1,
      "\"Each\" is singular, so the verb should be \"has\": Each of the engineers has submitted..."),
    q("What does \"burn the midnight oil\" mean?",
      ["Waste fuel", "Work late into the night", "Start a fire", "Wake up early"], 1,
      "The idiom means to stay up late working or studying."),
    q("Fill in the blank: Hardly had he reached the station ___ the train left.",
      ["than", "when", "then", "that"], 1,
      "\"Hardly/scarcely ... when\" and \"No sooner ... than\" are the correct pairs."),
    q("Choose one word for \"one who knows everything\".",
      ["Omnipotent", "Omniscient", "Omnipresent", "Ominous"], 1,
      "Omniscient = all-knowing. Omnipotent = all-powerful. Omnipresent = present everywhere."),
    q("Fill in the blank: He insisted ___ paying the bill.",
      ["to", "for", "on", "at"], 2,
      "The verb \"insist\" takes the preposition \"on\" before a gerund: insisted on paying."),
    q("Fill in the blank: If I ___ you, I would apologise.",
      ["am", "was", "were", "be"], 2,
      "For an imaginary or unreal situation, use the subjunctive \"were\" for all persons."),
    q("What does \"ubiquitous\" mean?",
      ["Very rare", "Found everywhere", "Extremely old", "Easy to break"], 1,
      "Ubiquitous describes something that seems to be present everywhere, like smartphones."),
    q("Fill in the blank: The new policy will have a significant ___ on sales.",
      ["affect", "effect", "affects", "effected"], 1,
      "\"Effect\" is the noun (a result). \"Affect\" is usually the verb (to influence)."),
    q("Choose the sentence with correct parallel structure.",
      ["She likes hiking, swimming and to ride bicycles.",
       "She likes hiking, swimming and riding bicycles.",
       "She likes to hike, swimming and riding bicycles.",
       "She likes hiking, to swim and riding bicycles."], 1,
      "Items in a list should share the same form. Here: hiking, swimming, riding."),
    q("Which sentence is correct?",
      ["Despite of the rain, we played.", "Despite the rain, we played.",
       "In spite the rain, we played.", "Despite from the rain, we played."], 1,
      "\"Despite\" is never followed by \"of\". \"In spite of\" is the longer form."),
    q("What does \"to mitigate\" mean?",
      ["To make worse", "To make less severe", "To ignore", "To repeat"], 1,
      "Mitigate means to reduce the seriousness or impact of something."),
    q("What does the phrasal verb \"call off\" mean?",
      ["Telephone someone", "Cancel", "Postpone by a day", "Shout loudly"], 1,
      "\"Call off\" means to cancel: The match was called off due to rain."),
    q("Change to passive voice: \"The manager approved the proposal.\"",
      ["The proposal approved the manager.", "The proposal was approved by the manager.",
       "The proposal is approved by the manager.", "The proposal has approved by the manager."], 1,
      "Simple past active becomes: object + was/were + past participle + by + subject."),
]

# ------------------------------------------------------------- REASONING
REASONING_BEGINNER = [
    q("Find the next number: 2, 4, 6, 8, ?",
      ["9", "10", "12", "14"], 1,
      "The numbers go up by 2 each time, so the next is 10."),
    q("Find the next number: 3, 6, 12, 24, ?",
      ["36", "42", "48", "30"], 2,
      "Each number is doubled: 24 x 2 = 48."),
    q("Which one is the odd one out?",
      ["Apple", "Banana", "Carrot", "Mango"], 2,
      "Apple, banana and mango are fruits. Carrot is a vegetable."),
    q("A is taller than B, and B is taller than C. Who is the tallest?",
      ["A", "B", "C", "Cannot be said"], 0,
      "A > B > C, so A is the tallest."),
    q("If A=1, B=2, C=3 and so on, what is the code for \"BAD\"?",
      ["214", "124", "241", "412"], 0,
      "B=2, A=1, D=4, so BAD = 214."),
    q("Today is Monday. What day will it be after 10 days?",
      ["Wednesday", "Thursday", "Friday", "Sunday"], 1,
      "10 = 7 + 3. After 7 days it is Monday again, then 3 more days gives Thursday."),
    q("A man walks 5 km north and then 5 km south. How far is he from the start?",
      ["10 km", "5 km", "0 km", "2.5 km"], 2,
      "He walks back along the same line, so he is back at the start: 0 km."),
    q("Who is your mother's only brother's son to you?",
      ["Brother", "Cousin", "Uncle", "Nephew"], 1,
      "Your mother's brother is your maternal uncle. His son is your cousin."),
    q("Find the next number: 1, 4, 9, 16, ?",
      ["20", "24", "25", "36"], 2,
      "These are squares: 1², 2², 3², 4², so next is 5² = 25."),
    q("What is the value of 5 + 3 x 2?",
      ["16", "11", "13", "10"], 1,
      "Multiplication comes before addition (BODMAS): 3 x 2 = 6, then 5 + 6 = 11."),
    q("Find the next letter: A, C, E, G, ?",
      ["H", "I", "J", "K"], 1,
      "Skip one letter each time: A, C, E, G, I."),
    q("Ravi is 7th from the left in a row of 15 students. What is his position from the right?",
      ["7th", "8th", "9th", "10th"], 2,
      "Position from right = total - position from left + 1 = 15 - 7 + 1 = 9."),
    q("Bird : Fly :: Fish : ?",
      ["Walk", "Swim", "Run", "Crawl"], 1,
      "A bird moves by flying. A fish moves by swimming."),
    q("The sum of two consecutive numbers is 37. What is the larger number?",
      ["17", "18", "19", "20"], 2,
      "The numbers are 18 and 19 (18 + 19 = 37). The larger is 19."),
    q("All roses are flowers. All flowers are plants. Are all roses plants?",
      ["Yes, definitely", "No", "Only some", "Cannot say"], 0,
      "Roses are inside flowers, and flowers are inside plants, so every rose is a plant."),
]

REASONING_ADVANCED = [
    q("Find the next number: 2, 6, 12, 20, 30, ?",
      ["40", "42", "44", "38"], 1,
      "The terms are n x (n+1): 1x2, 2x3, 3x4, 4x5, 5x6, so next is 6x7 = 42."),
    q("Find the next number: 2, 3, 5, 9, 17, ?",
      ["25", "31", "33", "35"], 2,
      "The differences are 1, 2, 4, 8, so the next difference is 16: 17 + 16 = 33."),
    q("Statements: Some A are B. All B are C.\nConclusions: I. Some A are C.  II. All A are C.",
      ["Only I follows", "Only II follows", "Both follow", "Neither follows"], 0,
      "The A's that are B must be C, so some A are C. But not all A are necessarily B, so II does not follow."),
    q("A man walks 8 m east, turns right and walks 6 m. How far is he from the start (straight line)?",
      ["14 m", "10 m", "12 m", "2 m"], 1,
      "He forms a right triangle with sides 8 and 6, so the distance is √(64+36) = 10 m."),
    q("A father is 3 times as old as his son. After 12 years he will be twice as old. How old is the son now?",
      ["10", "12", "14", "18"], 1,
      "3x + 12 = 2(x + 12) gives x = 12. Check: father 36 now, 48 later; son 24 later; 48 = 2 x 24."),
    q("If MANGO is written as NBOHP (every letter moves one step ahead), how is PEACH written?",
      ["QFBDI", "QEBDI", "PFBDI", "QFCDI"], 0,
      "P→Q, E→F, A→B, C→D, H→I, so PEACH = QFBDI."),
    q("Pointing to a man, a woman says, \"His mother is the only daughter of my mother.\" How is the woman related to the man?",
      ["Sister", "Mother", "Aunt", "Grandmother"], 1,
      "The only daughter of the woman's mother is the woman herself. So she is the man's mother."),
    q("Five friends P, Q, R, S, T sit in a row. P is at the left end, T is at the right end, S sits immediately to the right of P, and R does not sit next to T. Who sits in the middle?",
      ["Q", "R", "S", "T"], 1,
      "Order: P, S, _, _, T. R cannot be next to T, so R takes seat 3 and Q takes seat 4. The middle seat is R."),
    q("What is the angle between the hour and minute hands at 3:30?",
      ["60°", "75°", "90°", "105°"], 1,
      "At 3:30 the minute hand is at 180° and the hour hand at 105°. The difference is 75°."),
    q("If the 5th of a month is a Wednesday, what day is the 28th of the same month?",
      ["Thursday", "Friday", "Saturday", "Sunday"], 1,
      "28 - 5 = 23 days later. 23 = 21 + 2, so the day is two days after Wednesday: Friday."),
    q("In a class of 40 students, Riya's rank is 12th from the top. What is her rank from the bottom?",
      ["27th", "28th", "29th", "30th"], 2,
      "Rank from bottom = 40 - 12 + 1 = 29."),
    q("Which number is the odd one out? 8, 27, 64, 100, 125",
      ["27", "64", "100", "125"], 2,
      "8, 27, 64 and 125 are perfect cubes (2³, 3³, 4³, 5³). 100 is not."),
    q("A says \"B is lying\". B says \"C is lying\". C says \"A and B are both lying\". Who is telling the truth?",
      ["Only A", "Only B", "Only C", "A and C"], 1,
      "If B is truthful, C lies and A lies, and C's claim \"both lie\" is false because B is truthful. This is consistent. Assuming A or C is truthful leads to a contradiction."),
    q("Find the next pair: AZ, BY, CX, ?",
      ["DV", "DW", "EW", "DX"], 1,
      "The first letter moves forward (A, B, C, D) while the second moves backward (Z, Y, X, W): DW."),
    q("In a group of 50 people, 30 like tea, 25 like coffee and 10 like neither. How many like both?",
      ["10", "15", "20", "25"], 1,
      "40 people like at least one drink. 30 + 25 - both = 40, so both = 15."),
]

# ---------------------------------------------------------------- CODING
CODING_BEGINNER = [
    q("What is the output?", ["20", "14", "24", "9"], 1,
      "Multiplication happens before addition: 3 * 4 = 12, then 2 + 12 = 14.",
      code="print(2 + 3 * 4)"),
    q("What is the output?", ["3", "4", "5", "IARE"], 1,
      "len() returns the number of characters. \"IARE\" has 4.",
      code='print(len("IARE"))'),
    q("What is the output?", ["3", "4", "[1, 2, 3, 4]", "Error"], 1,
      "append() adds one item at the end, so the list now has 4 items.",
      code="x = [1, 2, 3]\nx.append(4)\nprint(len(x))"),
    q("What is the output?", ["1 2 3", "0 1 2", "0 1 2 3", "1 2"], 1,
      "range(3) gives 0, 1, 2. It starts at 0 and stops before 3.",
      code='for i in range(3):\n    print(i, end=" ")'),
    q("What is the output?", ["3.33", "3", "4", "1"], 1,
      "The // operator is floor division. 10 divided by 3 is 3 with remainder 1.",
      code="print(10 // 3)"),
    q("What is the output?", ["3", "1", "0", "3.33"], 1,
      "The % operator gives the remainder. 10 = 3 x 3 + 1, so the remainder is 1.",
      code="print(10 % 3)"),
    q("What is the output?", ["ab3", "ababab", "ab ab ab", "Error"], 1,
      "Multiplying a string by a number repeats it.",
      code='print("ab" * 3)'),
    q("Which data structure follows the LIFO (Last In, First Out) rule?",
      ["Queue", "Stack", "Array", "Tree"], 1,
      "A stack removes the most recently added item first, like a pile of plates."),
    q("What is the output?",
      ["<class 'int'>", "<class 'float'>", "<class 'str'>", "<class 'double'>"], 1,
      "3.0 has a decimal point, so Python treats it as a float.",
      code="print(type(3.0))"),
    q("What is the output?", ["h", "e", "l", "hello"], 1,
      "Indexing starts at 0: s[0] is 'h' and s[1] is 'e'.",
      code='s = "hello"\nprint(s[1])'),
    q("What is the output?", ["3", "3.5", "4", "3.0"], 1,
      "In Python 3, / always gives a decimal result: 7 / 2 = 3.5.",
      code="print(7 / 2)"),
    q("Which keyword is used to define a function in Python?",
      ["function", "define", "def", "fun"], 2,
      "Python functions start with def, for example: def add(a, b):"),
    q("What is the time complexity of accessing an array element by its index?",
      ["O(1)", "O(n)", "O(log n)", "O(n²)"], 0,
      "The position in memory is calculated directly from the index, so it takes constant time."),
    q("What is the output?", ["7", "10", "25", "32"], 2,
      "The ** operator means power: 5 squared is 25.",
      code="a = 5\nb = 2\nprint(a ** b)"),
    q("What is the output?", ["4", "10", "15", "5"], 1,
      "range(1, 5) gives 1, 2, 3, 4. Their sum is 10.",
      code="total = 0\nfor i in range(1, 5):\n    total += i\nprint(total)"),
]

CODING_ADVANCED = [
    q("What is the output?",
      ["[1] then [2]", "[1] then [1, 2]", "[1] then [2, 1]", "Error"], 1,
      "The default list is created once when the function is defined and is shared between calls. This is the classic mutable default argument trap.",
      code="def f(x, items=[]):\n    items.append(x)\n    return items\n\nprint(f(1))\nprint(f(2))"),
    q("What is the output?",
      ["[0, 1, 4, 9, 16]", "[0, 4, 16]", "[1, 9]", "[0, 2, 4]"], 1,
      "The comprehension keeps only even i (0, 2, 4) and squares them: 0, 4, 16.",
      code="print([i * i for i in range(5) if i % 2 == 0])"),
    q("What is the time complexity of binary search on a sorted array of n items?",
      ["O(n)", "O(log n)", "O(n log n)", "O(1)"], 1,
      "Each step halves the search space, so about log₂(n) steps are needed."),
    q("What is the output?",
      ["[1, 2, 3]", "[1, 2, 3, 4]", "[4]", "Error"], 1,
      "b = a does not copy the list. Both names point to the same list, so changing b changes a.",
      code="a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)"),
    q("What is the output?",
      ["False False", "False True", "True True", "True False"], 1,
      "An empty list is falsy. A non-empty list is truthy, even if it contains 0.",
      code="print(bool([]), bool([0]))"),
    q("What is the time complexity of this code?",
      ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"], 2,
      "The inner loop runs 0 + 1 + 2 + ... + (n-1) = n(n-1)/2 times, which is O(n²).",
      code="for i in range(n):\n    for j in range(i):\n        work()"),
    q("What is the output?",
      ["[0, 1, 2]", "[2, 2, 2]", "[0, 0, 0]", "Error"], 1,
      "The lambdas capture the variable i, not its value. By the time they run, i is 2.",
      code="fs = [lambda: i for i in range(3)]\nprint([f() for f in fs])"),
    q("Which of these cannot be used as a key in a Python dictionary?",
      ["A tuple of numbers", "A string", "A list", "An integer"], 2,
      "Dictionary keys must be hashable (immutable). Lists can change, so they are not hashable."),
    q("What is the output?",
      ["bcde", "bd", "ace", "bdf"], 1,
      "The slice [1:5:2] starts at index 1, stops before 5, and steps by 2: indexes 1 and 3, which are 'b' and 'd'.",
      code='print("abcdef"[1:5:2])'),
    q("What is the output?",
      ["8", "13", "21", "34"], 1,
      "This is the Fibonacci sequence: 0, 1, 1, 2, 3, 5, 8, 13. So g(7) = 13.",
      code="def g(n):\n    return n if n < 2 else g(n - 1) + g(n - 2)\n\nprint(g(7))"),
    q("Which data structure is normally used to implement Breadth-First Search (BFS)?",
      ["Stack", "Queue", "Heap", "Hash set only"], 1,
      "BFS visits nodes level by level, so it uses a queue (first in, first out). DFS uses a stack."),
    q("What is the worst-case time complexity of Quick Sort?",
      ["O(n log n)", "O(n)", "O(n²)", "O(log n)"], 2,
      "If the pivot is always the smallest or largest element (for example, an already sorted array with a bad pivot choice), partitions are unbalanced and it takes O(n²)."),
    q("What is the output?",
      ["True", "False", "Error", "None"], 1,
      "Floating-point numbers cannot represent 0.1 and 0.2 exactly, so the sum is 0.30000000000000004.",
      code="print(0.1 + 0.2 == 0.3)"),
    q("What is printed?",
      ["1", "A then 1", "1 then A", "A"], 1,
      "The finally block always runs before the function returns, so A is printed first, then print(f()) prints 1.",
      code='def f():\n    try:\n        return 1\n    finally:\n        print("A")\n\nprint(f())'),
    q("What is the space complexity of a recursive DFS on a binary tree of height h?",
      ["O(1)", "O(h)", "O(n²)", "O(log n) always"], 1,
      "The call stack holds at most one frame per level, so it uses O(h) space. For a skewed tree h can be n."),
]

BANK = {
    "english": {"beginner": ENGLISH_BEGINNER, "advanced": ENGLISH_ADVANCED},
    "reasoning": {"beginner": REASONING_BEGINNER, "advanced": REASONING_ADVANCED},
    "coding": {"beginner": CODING_BEGINNER, "advanced": CODING_ADVANCED},
}

LEVELS = ("beginner", "advanced")
QUESTIONS_PER_LIST = len(ENGLISH_BEGINNER)
